### PR TITLE
Update sample.json

### PR DESCRIPTION
**Pull request by LuiseFreese**
Corrected description and updated update date. Description was incorrect as the sample doesn’t register a new app in AD. we add a system assigned Managed Identity so that we don’t need an app Registration (with a secret or Certificate).

### CODE REVIEW

**Comment by pkbullock** [comment]
Thanks Luise, my bad should have checked that with you. Everyday is a learning day. 

Thanks for checking this. :-)

**Comment by LuiseFreese** [comment]
no worries. This is for a system assigned MI. 

For a user assigned MI, you would need an app registration and slightly different commands... would that be worth another sample?  @pkbullock

**Comment by pkbullock** [comment]
@LuiseFreese i think so, its a different scenario albeit similar. It would be a new sample 😊

**Comment by LuiseFreese** [comment]
ok, will submit it but then change the title so that its clear that we have system assigned and user assigned MI as different scenarios. 

You got me hooked :-)

**Pull request merged**
