### PR TITLE
Added spo-export-stream-classic-webparts

### PR DESCRIPTION
**Pull request by tecchan1107**
With the planned retirement of Stream and I thought it would be necessary to maintain Stream (Classic) Web Parts, I created a script that outputs a CSV of Stream (Classic) Web Parts and the pages that use them.

### CODE REVIEW

**Comment by pkbullock** [comment]
Hi @tecchan1107 - is this ready to merge?
こんにちは@tecchan1107-これはマージする準備ができていますか?

**Comment by tecchan1107** [comment]
Hi @pkbullock . There is no problem if you merge them!

Sorry for the repeated commits and fixes😣

**Comment by pkbullock** [comment]
Hey @tecchan1107, thank you for a perfect submission, appreciate you sharing with the community!! 👏😊 This should be live shortly 😊
ねえ@tecchan1107、完璧な提出をありがとう、コミュニティと共有していただきありがとうございます!👏😊 これはまもなく😊公開されるはずです

**Comment by tecchan1107** [comment]
Thank you so much @pkbullock !!

I looked at the other samples in PnP Script Samples, and it became better to fix this one and that one... As a result, I made so many fixes after the pull request. These fixes should have been made before the pull request😔

I'll be careful if I get another chance to do a pull request.

Once again ありがとうございました！！

**Pull request merged**
