### PR TITLE
Add new sample for retrieving external users in site groups in SharePoint Online.

### PR DESCRIPTION
**Pull request by martinlingstuyl**
This script shows how you can check if external users are added to site groups. It will show all external users across all site collections and the site groups they where added to.

### CODE REVIEW

**Comment by pkbullock** [comment]
Hey @martinlingstuyl , thank you!! 👏😊 This should be live shortly 😊
I noticed the sample included reference to another author, do you have details e..g GitHub Profile and/or Twitter handle so I can credit as well? Or is it all you?

**Comment by martinlingstuyl** [comment]
Hi @pkbullock,

I see the sample.json file is missing. I had filled it all out and added his name and github handle in there. 🙄
Shall I PR that?

**Comment by martinlingstuyl** [comment]
Oh wait, it's there. in the assets folder. 😂 It contains Bart-Jans github handle

**Comment by martinlingstuyl** [comment]
@bjdekker1982 is his twitter handle

**Comment by pkbullock** [comment]
Brilliant, I see that now - thank you.

**Pull request merged**
