### PR TITLE
Script Sample to Provision Home Page

### PR DESCRIPTION
**Pull request by reshmee011**
Script to provision Home Page to a SharePoint Site based on an already configured Page from a different SharePoint Site.

### CODE REVIEW

**Comment by pkbullock** [comment]
Hey Reshmee, thank you 👏 for your contribution - it is highly appreciated. This should be live shortly 😊

Just wondering, if there is a story behind this script, the wider business reason and how you came to the solution, have you thought about writing a post on PnP tech community?

@LuiseFreese would be happy to help set you up and support through the process.

**Comment by reshmee011** [comment]
I came up with the script to fulfil the shortcoming of site template to deploy a custom home page. It was not a possibility for me to use logic app or power automate to call PnP provisioning due to the lack of governance set up yet to use these components. After a team site is created using selected site template, I have a custom PowerShell script to update versioning settings, permission settings, set the custom Home Page and others.

**Comment by LuiseFreese** [comment]
Hey there @reshmee011 - thank you again - this is really great! I would love to have you as an author for the PnP blog - would you be interested?

**Comment by reshmee011** [comment]
Hi Luise

Yes, that sounds great. Please share the details of how I can join the PnP
blog?

**Comment by LuiseFreese** [comment]
Hi @reshmee011 

1. register at techcommunity.microsoft.com if you haven't already
2. sign in, select your profile
3. obtain your user id (not your email address) from the URL - its a number
4. send me this number so that I can add you as an author
5. once i did that, visit https://aka.ms/m365pnp/community/blog - you should now see an "create an article" button
6. hit this button and start writing. Reach out to me if you need any help. 
7. once you hit "submit for review"  I get a notification and can publish your article
8. your article will then go into my amplification pipeline, it gets tweeted out a a lot.

**Comment by LuiseFreese** [comment]
@reshmee011 you are now an author - please hard refresh the site :-) https://aka.ms/m365pnp/community/blog

**Comment by reshmee011** [comment]
Awesome, thanks! I can see the Create New Article button:)

**Pull request merged**
