### PR TITLE
New sample: How to automate a flow test

### PR DESCRIPTION
**Pull request by joshua-probst**
With the script example I would like to give a small instruction how to automate or monitor a flowtest. This is initially only a structure for a specific use case. However, you can adapt the script relatively easily for your requirements.

### CODE REVIEW

**Comment by pkbullock** [comment]
Hey @joshua-probst , thank you 👏 for your new MEGA sample - it is highly appreciated. This should be live shortly 😊

Have you registered for the PnP Recognition program, your submission will qualify for a badge :-)
Its opt in so please register here: https://pnp.github.io/recognitionprogram

**Comment by joshua-probst** [comment]
> Hey @joshua-probst , thank you 👏 for your new MEGA sample - it is highly appreciated. This should be live shortly 😊
> 
> Have you registered for the PnP Recognition program, your submission will qualify for a badge :-) Its opt in so please register here: https://pnp.github.io/recognitionprogram

Hi, 
I am already registered for the PnP Recognition program. However, this is my first contribution since the program exists. Is there anything else to do from my side?

**Comment by joshua-probst** [comment]
> Hey @joshua-probst , thank you 👏 for your new MEGA sample - it is highly appreciated. This should be live shortly 😊
> 
> Have you registered for the PnP Recognition program, your submission will qualify for a badge :-) Its opt in so please register here: https://pnp.github.io/recognitionprogram

Hi @pkbullock , 
just wanted to ask how i can claim or receive those badges? I already registered to the recognition program, but diddnt receive a badge. May you can help me because this is my first contribution since the program exists.

**Comment by pkbullock** [comment]
Hey @joshua-probst David Warner issues the badges periodically in batches it's not automated. They will likely come in the next batch.

**Pull request merged**
