### PR TITLE
added export powerapps details script

### PR DESCRIPTION
**Pull request by siddharth-vaghasia**
Added new script to export all the powerapps and its details in csv format with role assigments.

### CODE REVIEW

**Comment by pkbullock** [comment]
Hi @siddharth-vaghasia - thank you for the script, as there isnt a Power App type tab/metadata yet, I need to make adjustment to the site itself to support that, as your the first. 

I have added issue #158 for tracking. I will be able to merge this, once the adjustments are complete. Hope that is OK.
Again - thank you.

**Comment by siddharth-vaghasia** [comment]
Hey @pkbullock - it is more than okay. Happy that I was the first one to add a new script to this category and I do have one more that would be ready soon which will have a similar category..  that would add bulk users to PowerApps using CSV file..should I wait until confirmation to create PR for that?

**Comment by pkbullock** [comment]
You can submit PRs, I will process them when the site is updated 😊

**Comment by pkbullock** [comment]
Thank you @siddharth-vaghasia 👏 for this contribution - it is highly appreciated. This will be live shortly 😊

**Pull request merged**
