### PR TITLE
Added CLI for M365 version for script "Export SharePoint List Data to CSV with attachments"

### LINKED ISSUE #275: CLI for M365 version for script "Export SharePoint List Data to CSV with attachments"
🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Export SharePoint List Data to CSV with attachments](https://pnp.github.io/script-samples/spo-export-sharepoint-list-items-to-csv/README.html?tabs=pnpps).

🤔How
I think one of the best approach would be to use the following commands:

- [field-get](https://pnp.github.io/cli-microsoft365/cmd/spo/field/field-get/)
- [listitem-get](https://pnp.github.io/cli-microsoft365/cmd/spo/listitem/listitem-get/)
- [file-get](https://pnp.github.io/cli-microsoft365/cmd/spo/file/file-get/)

### PR DESCRIPTION
**Pull request by nanddeepn**
Added CLI for M365 version for script "Export SharePoint List Data to CSV with attachments"
Closes #275

### CODE REVIEW

**Comment by nanddeepn** [comment]
Hi @Adam-it 
Please review.

**Issue:**
The commands [m365 spo listitem list](https://pnp.github.io/cli-microsoft365/cmd/spo/listitem/listitem-list/) with parameter `--fields` does not seem to work with lookup columns.

When lookup column is passed to `--fields` parameter, it throws below error:
```
Error: The query to field 'Parent' is not valid. The $select query string must specify the target fields and the $expand
 query string must contains Parent.
```

Also, same error occurs when [m365 spo listitem get](https://pnp.github.io/cli-microsoft365/cmd/spo/listitem/listitem-get/) command is used with `--properties` parameter as lookup column

Except the above issue, the PR works fine.
Can you please verify if this is the case.

**Comment by Adam-it** [comment]
@nanddeepn your work is awesome 🤩. I will for sure have a look on this but on Monday as I am full with work over the weekend 😥, so please be patient 🙏.
as for the issues you described I think those are perfect for improvements in the CLI for M365 tool don't you think 🤔? I think we may open an issue referencing this script as example 😉. If you want I may add an issue or if you want to do it be my guest 😍. You may tag me in the issue if you want to engage me into the discussion 👍

**Comment by nanddeepn** [comment]
Thank you @Adam-it 
Have a nice weekend! Please take your time for review.

Meanwhile, I have created issue https://github.com/pnp/cli-microsoft365/issues/3391 at pnp/cli-microsoft365 repo.

**Review by Adam-it — APPROVED** [review]
pulled locally and tested
image

nothing to add
you rock 🤩

**Comment by pkbullock** [comment]
Awesome sample - thank you @nanddeepn this should be live shortly. 😊🎉

**Pull request merged**
