### PR TITLE
script sample for issue #419

### PR DESCRIPTION
**Pull request by ValerasNarbutas**
Good dau @pkbullock  and @Adam-it 
been a while i submited code, hope i am still doing it right :)
this is for issue #419

### CODE REVIEW

**Comment by ValerasNarbutas** [comment]
related to issue #416 . 
Example of creating AD app, add permissions to app and connect to Sharepoint using app id and secret

**Comment by ValerasNarbutas** [comment]
i might added 2 script samples in one commit :(
let me know if i need to separate them

**Comment by Adam-it** [comment]
thanks @ValerasNarbutas for considering my opinion 😊, but I will leave it to @pkbullock who is making awesome work in maintaining this repo 🤩 and I would not step into his shoes 👍.
If you want I may double check the script for any errors 🤔?
BTW thank you for contributing a sample to the PnP script sample gallery 👍 You rock 🤩

**Comment by pkbullock** [comment]
Hey @ValerasNarbutas and Happy New Year, thank you for both samples, these are awesome!! 👏😊 This should be live shortly 😊

**Pull request merged**
