### PR TITLE
Added Report Stream (Classic)  videos

### PR DESCRIPTION
**Pull request by ScoutmanPt**

### CODE REVIEW

**Comment by pkbullock** [comment]
Nice script - it will take longer than normal to process, need to make small adjustments to the site.

**Comment by ScoutmanPt** [comment]
@pkbullock  I'll be "dumping" all the pnpcandy stuff over here. It's about time.

**Comment by ScoutmanPt** [comment]
@pkbullock  I'll be "dumping" all the pnpcandy stuff over this repo. It's about time.:P

**Comment by pkbullock** [comment]
Wow 🤩 thank you, if you need any help creating pages or bulk import please reach out. 

Just out of interest how many scripts and do you think the site needs expanding to support other PowerShell/Command line tools?

**Comment by ScoutmanPt** [comment]
scripts are around 500 more or less. regarding other ps\cmd tools... well there's a couple of them that can be interesting to  have it here : 
PowerShell -: general samples to daily rotines,MsGraph, Az.xxx,Skype,MicrosoftDsc,SPMT, even SharePoint OnPremises could be interesting;
Cmd tools: azure cli 
Azure Pipelines (Yaml) gallery could also be interesting to have it  here (not really script but its aligned with the goal, "self-service cut and paste") Got a lot of requests on mean full examples on yaml.

Also to add more traction to the site, visual metrics on each script(already mentioned in a issue).

I'll be adding the remaining scripts for stream , and will start pushing the migration ones during this week.

**Comment by garrytrinder** [comment]
Just coming here to say thank you @ScoutmanPt that is an amazing gesture to the community 👏

**Comment by ScoutmanPt** [comment]
@garrytrinder ,  by the community 4 the community that's my creed. Didn't did it all  yet, due code sanitization , time and ... "huge perfection disability".
:P

**Comment by pkbullock** [comment]
Hey @ScoutmanPt , thank you 👏 for this sample, I made some small tweaks to the sample.json file, to ensure it will work when integrated in the master sample gallery. This should be live shortly 😊

**Pull request merged**
